### ISSUE TITLE
Web interface throws segmentation faults

### ISSUE THREAD

**Issue by stonor** [muccg/docker-devpi#11]
Hi, I've been running the latest Docker images (4.1.0 and 4.1.1) in two environments and I am getting a segmentation error in both.

I can create indexes, users and point pip to the index, but when I click around in the web interface, the Docker container crashes.
A request to /root/public seems to crash every time.
I tried to start the container in bash and run the entry point by hand get:

```
[req6] GET /root/public
Segmentation fault
```

/Anton

**Comment by aahunter** [comment]
seeing the same issue

```
Jun 12 11:36:43 ahunter-XPS-13-9343 docker[22949]: 2017-06-12 03:36:43,807 INFO  [req295] GET /root/public
Jun 12 11:36:44 ahunter-XPS-13-9343 systemd[1]: docker-devpi.service: Main process exited, code=exited, status=139/n/a
Jun 12 11:36:44 ahunter-XPS-13-9343 systemd[1]: docker-devpi.service: Unit entered failed state.
Jun 12 11:36:44 ahunter-XPS-13-9343 systemd[1]: docker-devpi.service: Failed with result 'exit-code'.
```

**Comment by marksutherland** [comment]
I've encountered this issue and attempted to decode the stacktrace, but it looks like I'd need to rebuild gdb with python support in the alpine container to get a python trace. For what it's worth, here's the c stacktrace decoded:

[stacktrace.txt](https://github.com/muccg/docker-devpi/files/1101752/stacktrace.txt)

**Comment by marksutherland** [comment]
Just checked 4.0.0 and it also segfaults. 2.5.3 doesn't provide the web interface.

**Comment by saily** [comment]
I had exactly the same issue when i was building devpi on alpine linux. I think this is somehow related to glibc library, if you use `FROM python:3.6` it works. See: https://hub.docker.com/r/widerin/openshift-devpi/

**Comment by skylerbunny** [comment]
Alpine Linux is based on musl, and not glibc. As I understand it, by default, musl allocates a very small stack size by default, 80kb.

I have opened an issue with devpi about 'being able to run devpi-server on Alpine Linux': https://github.com/devpi/devpi/issues/474 . It appears that 80kb simply isn't large enough for devpi-server when devpi-web is also installed. If this is the case, this could be resolved by devpi setting an explicit stack size to override an OS's library defaults.
