### ISSUE TITLE
New Devpi 4.6.0 is released

### ISSUE THREAD

**Issue by therealprof** [muccg/docker-devpi#14]
4.6.0 was released on 2018-07-13. Would it be possible to get the container updated?

**Comment by kierun** [comment]
Any update on this?

I hope this is not a dead project…

**Comment by grahame** [comment]
@kierun Hi - apologies for not replying earlier. Unfortunately we're no longer using this container internally, so we won't be supporting it. Please feel free to fork this if you would like.

I'll archive this repo to make it clear that it is unmaintained,
